

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.*;

public class Biodata_Mahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form BIODATAMAHASISWA
     */
    public Biodata_Mahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nnTextField = new javax.swing.JTextField();
        npmTextField = new javax.swing.JTextField();
        angkComBox = new javax.swing.JComboBox();
        kelasTextField = new javax.swing.JTextField();
        ipkTextField = new javax.swing.JTextField();
        rdlaki = new javax.swing.JRadioButton();
        rdperempuan = new javax.swing.JRadioButton();
        cbstatus = new javax.swing.JCheckBox();
        simpanButtom = new javax.swing.JButton();
        clearButtom = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabledata = new javax.swing.JTable();
        jumlah = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnsimpan1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FORM INPUT DATA MAHASISWA");

        jLabel2.setText("Nama");

        jLabel3.setText("Npm");

        jLabel4.setText("Kelas");

        jLabel6.setText("Angkatan");

        jLabel7.setText("IPK");

        jLabel8.setText("Jenis Kelamin");

        jLabel9.setText("Status");

        angkComBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023" }));
        angkComBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angkComBoxActionPerformed(evt);
            }
        });

        ipkTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipkTextFieldActionPerformed(evt);
            }
        });

        rdlaki.setText("Laki-Laki");

        rdperempuan.setText("Perempuan");

        cbstatus.setText("Aktif");

        simpanButtom.setBackground(new java.awt.Color(0, 0, 0));
        simpanButtom.setForeground(new java.awt.Color(255, 255, 255));
        simpanButtom.setText("SIMPAN");
        simpanButtom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanButtomMouseClicked(evt);
            }
        });

        clearButtom.setBackground(new java.awt.Color(0, 0, 0));
        clearButtom.setForeground(new java.awt.Color(255, 255, 255));
        clearButtom.setText("CLEAR");
        clearButtom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearButtomMouseClicked(evt);
            }
        });
        clearButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtomActionPerformed(evt);
            }
        });

        tabledata.setBackground(new java.awt.Color(102, 255, 204));
        tabledata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Npm", "Angkatan", "Kelas", "IPK", "J-Kelamin", "Status"
            }
        ));
        tabledata.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                tabledataVetoableChange(evt);
            }
        });
        jScrollPane1.setViewportView(tabledata);

        jLabel10.setText("JUMLAH DATA");

        btnsimpan1.setBackground(new java.awt.Color(255, 255, 51));
        btnsimpan1.setText("KELUAR");
        btnsimpan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsimpan1MouseClicked(evt);
            }
        });
        btnsimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpan1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(15, 15, 15)
                        .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnsimpan1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(npmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(kelasTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                                .addComponent(ipkTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                                .addComponent(angkComBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(nnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel7))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(126, 126, 126)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(rdlaki)
                                                .addGap(18, 18, 18)
                                                .addComponent(rdperempuan))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(cbstatus))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(simpanButtom)
                                        .addGap(39, 39, 39)
                                        .addComponent(clearButtom))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(142, 142, 142)
                                .addComponent(jLabel1)))
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(nnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdlaki)
                    .addComponent(rdperempuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(npmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cbstatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(angkComBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(kelasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ipkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpanButtom)
                    .addComponent(clearButtom))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(btnsimpan1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(783, 640));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ipkTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipkTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipkTextFieldActionPerformed

    private void simpanButtomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanButtomMouseClicked

        String ls_jk="";
        if(rdlaki.isSelected()){
            ls_jk = rdlaki.getText();
        }
        else if(rdperempuan.isSelected()){
            ls_jk = rdperempuan.getText();
        }
               String ls_status="";
        if (cbstatus.isSelected()){
            ls_status="Aktif";
        }else{
            ls_status="Tidak Aktif";
        }
        DefaultTableModel dataModel = (DefaultTableModel) tabledata.getModel();
            List list = new ArrayList<>();
            tabledata.setAutoCreateColumnsFromModel(true);
            list.add(nnTextField.getText());
            list.add(npmTextField.getText());
            list.add(angkComBox.getSelectedItem().toString());
            list.add(kelasTextField.getText());
            list.add(ipkTextField.getText());
            list.add(ls_jk);
            list.add(ls_status);
            dataModel.addRow(list.toArray());
             sum();
             JOptionPane.showMessageDialog(null, "Data berhasil disimpan "
    + "Information !!", "Information",
       JOptionPane.INFORMATION_MESSAGE);
        nnTextField.setText("");
        npmTextField.setText("");
        kelasTextField.setText("");
        ipkTextField.setText("");
        rdlaki.setSelected(false);
        rdperempuan.setSelected(false);
        cbstatus.setSelected(false);
        nnTextField.requestFocus();
    }//GEN-LAST:event_simpanButtomMouseClicked

    private void tabledataVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_tabledataVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tabledataVetoableChange

    private void clearButtomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtomMouseClicked
    JOptionPane.showMessageDialog(null, "Yakin membersihkan tabel?", "PERINGATAN???", JOptionPane.ERROR_MESSAGE);
        DefaultTableModel dataModel = (DefaultTableModel) tabledata.getModel(); 
            if (tabledata.getRowCount() > 0) {
                for (int i = tabledata.getRowCount() - 1; i > -1; i--) {
                    dataModel.removeRow(i);
                }
            }
    }//GEN-LAST:event_clearButtomMouseClicked
private void sum(){
        DefaultTableModel dataModel = (DefaultTableModel) tabledata.getModel();
        int jumlahdata = dataModel.getRowCount();
     
        jumlah.setText(Integer.toString(jumlahdata));
    }
    private void clearButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtomActionPerformed
        
    }//GEN-LAST:event_clearButtomActionPerformed

    private void angkComBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angkComBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_angkComBoxActionPerformed

    private void btnsimpan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsimpan1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsimpan1MouseClicked

    private void btnsimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpan1ActionPerformed
        // TODO add your handling code here:
        String Tanya = "Apakah Anda Yakin Ingin Keluar Aplikasi?";
        Boolean Yakin = JOptionPane.showConfirmDialog(rootPane, Tanya)==
                JOptionPane.YES_OPTION;
        if (Yakin){
        System.exit(0);
    }//GEN-LAST:event_btnsimpan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Biodata_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Biodata_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Biodata_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Biodata_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Biodata_Mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox angkComBox;
    private javax.swing.JButton btnsimpan1;
    private javax.swing.JCheckBox cbstatus;
    private javax.swing.JButton clearButtom;
    private javax.swing.JTextField ipkTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField kelasTextField;
    private javax.swing.JTextField nnTextField;
    private javax.swing.JTextField npmTextField;
    private javax.swing.JRadioButton rdlaki;
    private javax.swing.JRadioButton rdperempuan;
    private javax.swing.JButton simpanButtom;
    private javax.swing.JTable tabledata;
    // End of variables declaration//GEN-END:variables
}
